In [8]:
objects = [
    {
    "Obj1_url":"/media/lucap/big_data/datasets/pairwise/ali/breaking_bad_statue_pair1/breaking_bad_cat_statue_piece1.ply",
    "Obj2_url":"/media/lucap/big_data/datasets/pairwise/ali/breaking_bad_statue_pair1/breaking_bad_cat_statue_piece2.ply",
    "small_object":30000,"large_object":30000,
    #to1,to2,to3 -> always fixed for the object creation (i fixed it for almost of them)
    "to1":100 ,"to2":100, "to3":100,
    #tb1,tb2,tb3 -> border paramters depend on the nature of the object
    "tb1":0.1 ,"tb2":1, "tb3":0.1,
    #dilation_size , thre -> size of the dilation and threshold applied depend on each object
    "dilation_size":0.02,"thre":0.96},
    {
    "Obj1_url":"data_test/pairwise/breaking_bad_cat_artifact_pair2/breaking_bad_cat_artifact_piece2.ply",
    "Obj2_url":"data_test/pairwise/breaking_bad_cat_artifact_pair2/breaking_bad_cat_artifact_piece3.ply",
    "small_object":30000,"large_object":30000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":1, "tb3":0.1,
    "dilation_size":0.02,"thre":0.96},
    {
    "Obj1_url":"data_test/pairwise/breaking_bad_cat_artifact_pair1/breaking_bad_cat_artifact_piece1.ply",
    "Obj2_url":"data_test/pairwise/breaking_bad_cat_artifact_pair1/breaking_bad_cat_artifact_piece3.ply",
    "small_object":30000,"large_object":30000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":1, "tb3":0.1,
    "dilation_size":0.02,"thre":0.96},
    {
    "Obj1_url":"data_test/breaking_bad/mirror/7fe270a9cb7621ed157bba5da16c1cd3/mode_1/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/mirror/7fe270a9cb7621ed157bba5da16c1cd3/mode_1/piece_1.obj",
    "small_object":300000,"large_object":300000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.004,"thre":0.93
    },
     {
    "Obj1_url":"data_test/breaking_bad/mug/fractured_73/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/mug/fractured_73/piece_1.obj",
    "small_object":300000,"large_object":300000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.01,"thre":0.93
    },
     {
    "Obj1_url":"data_test/breaking_bad_2/Cookie/fractured_46/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad_2/Cookie/fractured_46/piece_1.obj",
    "small_object":40000,"large_object":80000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":100 ,"tb2":100, "tb3":100,
    "dilation_size":0.004,"thre":0.93
    },
     {
    "Obj1_url":"data_test/breaking_bad_2/Cookie/fractured_52/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad_2/Cookie/fractured_52/piece_1.obj",
    "small_object":40000,"large_object":80000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":100 ,"tb2":100, "tb3":100,
    "dilation_size":0.004,"thre":0.93
    },
     {
    "Obj1_url":"data_test/breaking_bad_2/Cookie/fractured_70/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad_2/Cookie/fractured_70/piece_1.obj",
    "small_object":40000,"large_object":80000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":100 ,"tb2":100, "tb3":100,
    "dilation_size":0.004,"thre":0.93
    },
     {
    "Obj1_url":"data_test/breaking_bad/WineBottle/fractured_14/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/WineBottle/fractured_14/piece_1.obj",
    "small_object":40000,"large_object":100000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.006,"thre":0.97
    },
     {
    "Obj1_url":"data_test/breaking_bad/WineBottle/fractured_3/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/WineBottle/fractured_3/piece_1.obj",
    "small_object":30000,"large_object":80000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.01,"thre":0.97
    },
     {
    "Obj1_url":"data_test/breaking_bad/PillBottle/fractured_40/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/PillBottle/fractured_40/piece_1.obj",
    "small_object":100000,"large_object":200000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.01,"thre":0.95
    },
     {
    "Obj1_url":"data_test/breaking_bad/DrinkBottle/fractured_62/piece_0.obj",
    "Obj2_url":"data_test/breaking_bad/DrinkBottle/fractured_62/piece_1.obj",
    "small_object":100000,"large_object":200000,
    "to1":100 ,"to2":100, "to3":100,
    "tb1":0.1 ,"tb2":0.1, "tb3":0.1,
    "dilation_size":0.008,"thre":0.93
    }
    
]

In [9]:
def get_winner_pair(test):
    import scipy
    from copy import copy
    i = 0
    winner_index = -1
    winner_value = 10000000
    arr = []
    for o1,o2,R_T in test.result_transformation_arr:
    #     print(o1,o2)
        obj1 = test.Obj1_array[o1]
        obj2 = test.Obj2_array[o2]
        obj2_tmp = copy(obj2)
        obj2_tmp.pcd = copy(obj2.pcd)
        obj2_tmp.pcd.transform(R_T)
    #     print(scipy.spatial.distance.directed_hausdorff(list(obj2_tmp.pcd.points), list(obj1.pcd.points), seed=0))
    #     print(scipy.spatial.distance.directed_hausdorff(list(obj1.pcd.points),list(obj2_tmp.pcd.points) , seed=0))
        chamfer_value = chamfer_distance(list(obj2_tmp.pcd.points),list(obj1.pcd.points))
        arr.append({"index":i,"o1":o1,"o2":o2,"chamfer":chamfer_value})
        if winner_value>chamfer_value:
            winner_index = i
            winner_value = chamfer_value
        i+=1
    chamfer_df = pd.DataFrame(arr)
    return chamfer_df.sort_values('chamfer')
import numpy as np
from sklearn.neighbors import NearestNeighbors


def chamfer_distance(x, y, metric='l2', direction='bi'):
    """Chamfer distance between two point clouds
    Parameters
    ----------
    x: numpy array [n_points_x, n_dims]
        first point cloud
    y: numpy array [n_points_y, n_dims]
        second point cloud
    metric: string or callable, default ‘l2’
        metric to use for distance computation. Any metric from scikit-learn or scipy.spatial.distance can be used.
    direction: str
        direction of Chamfer distance.
            'y_to_x':  computes average minimal distance from every point in y to x
            'x_to_y':  computes average minimal distance from every point in x to y
            'bi': compute both
    Returns
    -------
    chamfer_dist: float
        computed bidirectional Chamfer distance:
            sum_{x_i \in x}{\min_{y_j \in y}{||x_i-y_j||**2}} + sum_{y_j \in y}{\min_{x_i \in x}{||x_i-y_j||**2}}
    """
    
    if direction=='y_to_x':
        x_nn = NearestNeighbors(n_neighbors=1, leaf_size=1, algorithm='kd_tree', metric=metric).fit(x)
        min_y_to_x = x_nn.kneighbors(y)[0]
        chamfer_dist = np.mean(min_y_to_x)
    elif direction=='x_to_y':
        y_nn = NearestNeighbors(n_neighbors=1, leaf_size=1, algorithm='kd_tree', metric=metric).fit(y)
        min_x_to_y = y_nn.kneighbors(x)[0]
        chamfer_dist = np.mean(min_x_to_y)
    elif direction=='bi':
        x_nn = NearestNeighbors(n_neighbors=1, leaf_size=1, algorithm='kd_tree', metric=metric).fit(x)
        min_y_to_x = x_nn.kneighbors(y)[0]
        y_nn = NearestNeighbors(n_neighbors=1, leaf_size=1, algorithm='kd_tree', metric=metric).fit(y)
        min_x_to_y = y_nn.kneighbors(x)[0]
        chamfer_dist = np.mean(min_y_to_x) + np.mean(min_x_to_y)
    else:
        raise ValueError("Invalid direction type. Supported types: \'y_x\', \'x_y\', \'bi\'")
        
    return chamfer_dist

In [10]:
import ast

from runner import test
import numpy as np

object_number = 0

#objects
Obj1_url = objects[object_number]["Obj1_url"]
Obj2_url = objects[object_number]["Obj2_url"]
print(Obj1_url,Obj2_url)

#Before Evaluate do a Rotation and translation of
init_R_T = ((0.2, 0.2, 0.1), (-0.5, -0.5, -0.5))


#pipline name and pipline parameters
pipline_name = "general_pipeline"

#sampling
large_object = objects[object_number]["large_object"]
small_object = objects[object_number]["small_object"]


N = 15
Object_t1 = objects[object_number]["to1"]
Object_t2 = objects[object_number]["to2"]
Object_t3 = objects[object_number]["to3"]

border_t1 = objects[object_number]["tb1"]
border_t2 = objects[object_number]["tb1"]
border_t3 = objects[object_number]["tb1"]


#threshold for corner
thre = objects[object_number]["thre"]

dilation_size = objects[object_number]["dilation_size"]

pipline_variables = (small_object, large_object, N, Object_t1, Object_t2,
                     Object_t3, border_t1, border_t2, border_t3, dilation_size, thre)

#test
test_name = "ICP_test"

# eval 

eval_list = ["rms"]

test_breaking_thin = test(Obj2_url, Obj1_url, init_R_T, pipline_name, pipline_variables, test_name, eval_list, show_results = True, save_results=False)

my_results = test_breaking_thin.run()

/media/lucap/big_data/datasets/pairwise/ali/breaking_bad_statue_pair1/breaking_bad_cat_statue_piece1.ply /media/lucap/big_data/datasets/pairwise/ali/breaking_bad_statue_pair1/breaking_bad_cat_statue_piece2.ply
_________________________First Object_________________________
start
piece2.ply
small object
my number is ->  0.0042087623291015615
starting init
starting calculating atts


100%|██████████| 29839/29839 [00:05<00:00, 5168.19it/s]


my radius is :  0.0070102561123232005
342635
After graph 29839
constructing borders
3320
shortest_allowed_branch_length 576.1944116355173
smallest_isolated_island_length 576.1944116355173
shortest_cycle_length 576.1944116355173
my radius is :  0.013630894909184857
73808
After graph 3078
After Pruning 0
After Pruning 186
dilation and segmentation
borders dilated


220440it [31:23, 143.96it/s]                          

19185


282689it [40:07, 149.39it/s]

5643


283046it [40:11, 140.59it/s]

31


283066it [40:12, 43.32it/s] 

2


283074it [40:23, 116.82it/s]


got faces
KNN Radius :  0.0070102561123232005
0
expanded
coloring
_________________________Second Object_________________________
start
piece1.ply
small object
my number is ->  0.009152338623046877
starting init
starting calculating atts


100%|██████████| 29937/29937 [00:05<00:00, 5697.69it/s]


my radius is :  0.014905101449387032
324781
After graph 29937
constructing borders
6201
shortest_allowed_branch_length 787.4642849044012
smallest_isolated_island_length 787.4642849044012
shortest_cycle_length 787.4642849044012
my radius is :  0.025055606764133397
104373
After graph 5414
After Pruning 0
After Pruning 550
dilation and segmentation
borders dilated


110677it [09:22, 230.27it/s]                          

10001


198353it [16:57, 178.51it/s]

8733


219571it [18:47, 183.92it/s]

1885


233323it [19:55, 219.61it/s]

1264


241517it [20:37, 168.27it/s]

749


247218it [21:05, 190.11it/s]

508


252330it [21:31, 241.93it/s]

425


256562it [21:53, 157.39it/s]

377


258629it [22:02, 253.59it/s]

185


259306it [22:05, 229.76it/s]

63
1


259409it [22:07, 109.57it/s]

7


259530it [22:07, 201.96it/s]

13


259650it [22:09, 135.94it/s]

14


260276it [22:12, 208.69it/s]

54


260314it [22:14, 49.43it/s] 

1


260840it [22:17, 252.80it/s]

58


261133it [22:19, 211.53it/s]

28


261161it [22:20, 86.98it/s] 

2


261197it [22:22, 194.60it/s]


3
got faces
KNN Radius :  0.014905101449387032
0
expanded
coloring
_________________________Registeration_________________________
_________________________Evaluation_________________________


In [14]:
get_winner_pair(test_breaking_thin)

index  o1  o2   chamfer
38     38   2  12  0.018883
35     35   2   9  0.021140
16     16   1   3  0.022329
37     37   2  11  0.024341
19     19   1   6  0.040491
17     17   1   4  0.046516
36     36   2  10  0.047076
18     18   1   5  0.048864
20     20   1   7  0.055706
32     32   2   6  0.060687
34     34   2   8  0.065068
21     21   1   8  0.065317
15     15   1   2  0.067317
33     33   2   7  0.085766
31     31   2   5  0.086873
2       2   0   2  0.101820
3       3   0   3  0.102356
23     23   1  10  0.102554
4       4   0   4  0.111756
24     24   1  11  0.115562
25     25   1  12  0.117075
22     22   1   9  0.126336
29     29   2   3  0.131253
28     28   2   2  0.137638
7       7   0   7  0.140623
30     30   2   4  0.145733
6       6   0   6  0.149122
5       5   0   5  0.151100
14     14   1   1  0.160621
8       8   0   8  0.163949
10     10   0  10  0.187993
9       9   0   9  0.193233
11     11   0  11  0.199909
12     12   0  12  0.205061
1       1   0   1  0.222045
0       0   0   0  0.228392
13     13   1   0  0.299997
27     27   2   1  0.308392
26     26   2   0  0.430220

In [12]:
import pandas as pd
df_breaking_3 = pd.DataFrame(test_breaking_thin.results)
df_breaking_3["total"] = df_breaking_3["R_error"]+df_breaking_3["T_error"]
df_breaking_3.sort_values('T_error')

o1  o2   R_error   T_error     total
26   2   0  4.743880  0.447164  5.191045
9    0   9  4.808789  0.513477  5.322266
8    0   8  5.066918  0.523393  5.590311
30   2   4  3.582361  0.540039  4.122400
2    0   2  5.834852  0.575411  6.410263
22   1   9  4.158616  0.575826  4.734442
15   1   2  5.712548  0.600581  6.313129
1    0   1  4.755644  0.691743  5.447387
7    0   7  5.240430  0.696774  5.937204
14   1   1  5.369437  0.752640  6.122077
13   1   0  4.019568  0.764198  4.783766
29   2   3  5.731889  0.813619  6.545508
28   2   2  4.269083  0.818636  5.087719
4    0   4  4.225619  0.823522  5.049141
33   2   7  5.198108  0.865212  6.063319
32   2   6  5.026774  0.882908  5.909682
0    0   0  4.580944  0.949450  5.530394
31   2   5  4.473409  1.016841  5.490249
3    0   3  5.904567  1.055409  6.959975
34   2   8  3.762399  1.064832  4.827231
37   2  11  5.744999  1.079058  6.824057
27   2   1  5.308934  1.096100  6.405033
11   0  11  5.103382  1.166466  6.269847
16   1   3  5.386126  1.215054  6.601180
18   1   5  4.621942  1.220428  5.842370
35   2   9  5.402705  1.243174  6.645879
10   0  10  5.712017  1.253866  6.965883
21   1   8  6.044472  1.377810  7.422282
20   1   7  3.741585  1.395336  5.136921
38   2  12  6.052081  1.410345  7.462426
17   1   4  6.686619  1.417654  8.104273
5    0   5  4.903390  1.426071  6.329461
25   1  12  4.531388  1.449728  5.981116
19   1   6  5.276869  1.510313  6.787183
36   2  10  5.656303  1.550191  7.206493
24   1  11  6.138627  1.574988  7.713615
6    0   6  6.162190  1.724503  7.886694
12   0  12  6.349331  1.878143  8.227474
23   1  10  5.702229  1.881114  7.583343

In [123]:
test_breaking_thin.draw_registration_result_original_color(test_breaking_thin.Obj1,test_breaking_thin.Obj2,test_breaking_thin.result_transformation_arr[5][2])

In [15]:
for tr in test_breaking_thin.result_transformation_arr:
    print('\n', tr[2])


 [[-0.73395405  0.10390109 -0.6712049  -0.480245  ]
 [-0.34095372  0.79832915  0.49640822  0.54276208]
 [ 0.5874198   0.59319063 -0.55051145  0.4866419 ]
 [ 0.          0.          0.          1.        ]]

 [[ 0.81856395 -0.42347742  0.38809786  0.83409755]
 [ 0.48775095  0.86928981 -0.08021364  0.6023764 ]
 [-0.30340085  0.25495509  0.91812081  1.06712842]
 [ 0.          0.          0.          1.        ]]

 [[ 0.80940548 -0.43573069 -0.39370234  0.14897403]
 [ 0.40710353  0.89951078 -0.15857826  0.63977392]
 [ 0.42323692 -0.0319235   0.90545646  0.95088532]
 [ 0.          0.          0.          1.        ]]

 [[ 0.91438321 -0.39537574  0.08707102  0.22732953]
 [-0.30298319 -0.52564774  0.79491864 -0.13002253]
 [-0.26852286 -0.75324131 -0.60043567 -0.29196119]
 [ 0.          0.          0.          1.        ]]

 [[ 0.64428848  0.42690508  0.63454268  1.0258854 ]
 [ 0.55099071  0.31629397 -0.77224825  0.03738081]
 [-0.53037872  0.84717777 -0.03143617  0.15005799]
 [ 0.          0.

In [18]:
test_breaking_thin.draw_registration_result_original_color(test_breaking_thin.Obj1,test_breaking_thin.Obj2,test_breaking_thin.result_transformation_arr[26][2])

In [21]:
for o1,o2,R_T in test_breaking_thin.result_transformation_arr:
    print(f"obj1: {o1}, obj2: {o2}, \n{R_T}")

obj1: 0, obj2: 0, 
[[-0.73395405  0.10390109 -0.6712049  -0.480245  ]
 [-0.34095372  0.79832915  0.49640822  0.54276208]
 [ 0.5874198   0.59319063 -0.55051145  0.4866419 ]
 [ 0.          0.          0.          1.        ]]
obj1: 0, obj2: 1, 
[[ 0.81856395 -0.42347742  0.38809786  0.83409755]
 [ 0.48775095  0.86928981 -0.08021364  0.6023764 ]
 [-0.30340085  0.25495509  0.91812081  1.06712842]
 [ 0.          0.          0.          1.        ]]
obj1: 0, obj2: 2, 
[[ 0.80940548 -0.43573069 -0.39370234  0.14897403]
 [ 0.40710353  0.89951078 -0.15857826  0.63977392]
 [ 0.42323692 -0.0319235   0.90545646  0.95088532]
 [ 0.          0.          0.          1.        ]]
obj1: 0, obj2: 3, 
[[ 0.91438321 -0.39537574  0.08707102  0.22732953]
 [-0.30298319 -0.52564774  0.79491864 -0.13002253]
 [-0.26852286 -0.75324131 -0.60043567 -0.29196119]
 [ 0.          0.          0.          1.        ]]
obj1: 0, obj2: 4, 
[[ 0.64428848  0.42690508  0.63454268  1.0258854 ]
 [ 0.55099071  0.31629397 -0.77224