In [1]:
from runner import test

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [10]:
import numpy as np

#objects
Obj1_url ="data_test/pairwise/tuwien_brick_pair1/brick_part01.ply" 
Obj2_url ="data_test/pairwise/tuwien_brick_pair1/brick_part02.ply" 

#Before Evaluate do a Rotation and translation of
init_R_T = [( 0 ,0 ,0),( 2,0,0 )]


#pipline name and pipline parameters
pipline_name = "pipline_2"

N = 50
t1 = 10
t2 = 10
t3 = 10


#threshold for corner
thre = 0.93

pipline_variables = (N, t1, t2, t3, thre)

#test
test_name = "ICP_test"

# eval 

eval_list = ["rms"]


In [11]:
test1 = test(Obj2_url, Obj1_url, init_R_T, pipline_name, pipline_variables, test_name, eval_list, show_results = True, save_results=False)

In [12]:
my_results = test1.run()

start
starting init


C:\Users\alial\Documents\THESIS\Fragment.py:163: RuntimeWarning: invalid value encountered in true_divide
  e_vectors_dir = e_vectors/np.repeat(e_vectors_mag.reshape(e_vectors_mag.shape[0],e_vectors_mag.shape[1],1),3,axis=2)


create graph
my radius is :  0.08184104309739208


100%|██████████████████████████████████████████████████████████████████████████| 14951/14951 [00:05<00:00, 2519.19it/s]


After graph 14951
After Pruning 14691
4483
2819
2442
1267
202
2
1
1
1
1
start
starting init
create graph
my radius is :  0.14710890279379174


100%|██████████████████████████████████████████████████████████████████████████| 14949/14949 [00:07<00:00, 1957.47it/s]


After graph 14949
After Pruning 14671
2487
1402
1379
1323
1137
933
760
244
40
24
[[1. 0. 0. 2.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 1.  0.  0. -2.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]
[[ 0.50554406 -0.81467955  0.28411693 -3.60508397]
 [ 0.78140745  0.5719374   0.24957967  0.32370256]
 [-0.36582456  0.09583757  0.92573622  0.61866106]
 [ 0.          0.          0.          1.        ]]
{'R_error': 3.7835760033906447, 'T_error': 1.750376929828592}
[[-0.46167936  0.8006593   0.38183354 -2.30164526]
 [-0.70947151 -0.59167616  0.38284396  3.35833119]
 [ 0.53244938 -0.09414887  0.84120964 -0.01197798]
 [ 0.          0.          0.          1.        ]]
{'R_error': 4.654955967470476, 'T_error': 3.3718721422216067}
[[ 0.34330991  0.52586528  0.77820564 -1.03691537]
 [-0.50288282  0.80270887 -0.32057345 -0.03989561]
 [-0.79325101 -0.2812902   0.54002653  2.71942619]
 [ 0.          0.          0.          1.        ]]
{'R_error': 5.493710680367039, 'T_error': 

In [14]:
test1.results

[(0, 0, {'R_error': 3.783576003390645, 'T_error': 4.9666670558278865}),
 (0, 1, {'R_error': 4.654955967470468, 'T_error': 5.087404664124148}),
 (0, 2, {'R_error': 5.493710680367048, 'T_error': 4.737562270014474}),
 (0, 3, {'R_error': 5.006768431884276, 'T_error': 8.192025741704832}),
 (0, 4, {'R_error': 5.568819720428778, 'T_error': 7.479872637931199}),
 (0, 5, {'R_error': 5.19067249228614, 'T_error': 3.61249456703497}),
 (0, 6, {'R_error': 3.6260033258334574, 'T_error': 3.691100559746769}),
 (0, 7, {'R_error': 4.689573962508487, 'T_error': 7.821855143039237}),
 (0, 8, {'R_error': 5.341493900767535, 'T_error': 4.812093175615162}),
 (0, 9, {'R_error': 5.003293807410059, 'T_error': 4.1407971207909755}),
 (1, 0, {'R_error': 4.5476429879793745, 'T_error': 4.991053640592028}),
 (1, 1, {'R_error': 4.088314017563491, 'T_error': 6.636408460315158}),
 (1, 2, {'R_error': 4.788917852102675, 'T_error': 4.027174387467618}),
 (1, 3, {'R_error': 5.087196840473193, 'T_error': 9.484204468947738}),
 (1,

In [15]:
import pandas as pd
df = pd.DataFrame(test1.results)
df["error"] = [Error["R_error"]+Error["T_error"] for o1,o2,Error in test1.results]

In [16]:
test1.Obj2_array

In [17]:
df.sort_values('error')

0  1                                                  2      error
89  8  9    {'R_error': 0.0, 'T_error': 3.2411728199322565}   3.241173
85  8  5     {'R_error': 0.0, 'T_error': 3.325578654812233}   3.325579
82  8  2     {'R_error': 0.0, 'T_error': 3.484788537638536}   3.484789
88  8  8    {'R_error': 0.0, 'T_error': 3.6172505077258728}   3.617251
65  6  5    {'R_error': 0.0, 'T_error': 3.6527338956281805}   3.652734
.. .. ..                                                ...        ...
33  3  3  {'R_error': 5.083216263333758, 'T_error': 8.09...  13.180309
3   0  3  {'R_error': 5.006768431884276, 'T_error': 8.19...  13.198794
14  1  4  {'R_error': 5.557834735994321, 'T_error': 8.67...  14.228778
13  1  3  {'R_error': 5.087196840473193, 'T_error': 9.48...  14.571401
24  2  4  {'R_error': 5.858917507386237, 'T_error': 8.87...  14.730402

[100 rows x 4 columns]

In [22]:
df

0  1                                                  2      error
0   0  0  {'R_error': 3.783576003390645, 'T_error': 4.96...   8.750243
1   0  1  {'R_error': 4.654955967470468, 'T_error': 5.08...   9.742361
2   0  2  {'R_error': 5.493710680367048, 'T_error': 4.73...  10.231273
3   0  3  {'R_error': 5.006768431884276, 'T_error': 8.19...  13.198794
4   0  4  {'R_error': 5.568819720428778, 'T_error': 7.47...  13.048692
.. .. ..                                                ...        ...
95  9  5     {'R_error': 0.0, 'T_error': 4.830547681624433}   4.830548
96  9  6     {'R_error': 0.0, 'T_error': 5.480369105324179}   5.480369
97  9  7       {'R_error': 0.0, 'T_error': 8.6327180118274}   8.632718
98  9  8     {'R_error': 0.0, 'T_error': 6.021781341685509}   6.021781
99  9  9     {'R_error': 0.0, 'T_error': 5.460530051784335}   5.460530

[100 rows x 4 columns]

In [23]:
from copy import copy
source = copy(test1.Obj1_array[0])
source.pcd = copy(source.pcd)
target = copy(test1.Obj2_array[0])
target.pcd = copy(target.pcd)
test1.draw_registration_result_original_color(target,source,test1.result_transformation_arr[0][2])

In [ ]:
test1.Obj1_array[1].pcd.points

In [ ]:
import open3d as o3d
o3d.visualization.draw_geometries([])

In [ ]:
test1.show_before()

In [ ]:
test1.show_after()

In [ ]:
import helper
import numpy as np
import ast
import re
s = '''[[  0.86216055  -0.05210942  -0.50394821  11.1895856 ]
 [ -0.07712327   0.969605    -0.23220281   5.7623569 ]
 [  0.50073065   0.23906224   0.83193633 -41.70132799]
 [  0.           0.           0.           1.        ]]
'''
print(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
M = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
print(M)
RST = np.asarray(M)
R,T = helper.decompose(RST)
print(R)
print(T%3.14)

In [ ]:
import transforms3d
Tdash, Rdash, Zdash, Sdash = transforms3d.affines.decompose(RST)

In [ ]:
Sdash

In [ ]:
s = '''[[ 1.          0.          0.          0.        ]
 [ 0.          0.92106099 -0.38941834  0.        ]
 [ 0.          0.38941834  0.92106099  0.        ]
 [ 0.          0.          0.          1.        ]]'''
print(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
M = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
print(M)
RST = np.asarray(M)
R,T = helper.decompose(RST)
print(R)
print(T)

In [ ]:
init_R = '''[[ 1.          0.          0.        ]
 [ 0.          0.92106099 -0.38941834]
 [ 0.          0.38941834  0.92106099]]
'''
init_R = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', init_R).splitlines()))
init_R

In [ ]:
optimal = np.eye(3)
results = np.matmul(R,np.transpose(init_R))
R_error = (np.sqrt(np.sum(np.square(optimal - results))))
R_error = (np.sqrt(np.sum(np.square(T - results))))

In [ ]:
R_error

In [ ]:
test1.show_before()

In [ ]:
test1.show_after()

In [ ]:
test1.save_test()

In [ ]:
import pandas as pd
import os
from pathlib import Path 
d =  {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(d)
path = os.path.join("results","ali",'out.csv')
df.to_csv(path)  

In [ ]:
import open3d.t.pipelines.registration as treg