In [1]:
from runner import test


Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
import numpy as np

#objects
Obj1_url ="data_test/pairwise/repair_group8_pair2/RPf_00059_gt.ply" 
Obj2_url ="data_test/pairwise/repair_group8_pair2/RPf_00061_gt.ply" 

#Before Evaluate do a Rotation and translation of
init_R_T = [( 0 , 0 , 0),( 0, -0.6, 0 )]


#pipline name and pipline parameters
pipline_name = "pipline_1"

N = 15
t1 = 2
t2 = 2
t3 = 2


#threshold for corner
thre = 0.99

pipline_variables = (N, t1, t2, t3, thre)

#test
test_name = "ICP_test"

# eval 

eval_list = ["rms"]


In [3]:
test1 = test(Obj2_url, Obj1_url, init_R_T, pipline_name, pipline_variables, test_name, eval_list, show_results = False, save_results=True)

In [4]:
test1.run()

start
[Open3D WARNING] Read PLY failed: unable to read file: data_test/pairwise/repair_group8_pair2/RPf_00061_gt.ply


RPly: Error reading 'y' of 'vertex' number 533637


starting init


/home/ali.alagrami/project/AAFR/Fragment.py:163: RuntimeWarning: invalid value encountered in divide
  e_vectors_dir = e_vectors/np.repeat(e_vectors_mag.reshape(e_vectors_mag.shape[0],e_vectors_mag.shape[1],1),3,axis=2)


starting threshold
create graph
my radius is :  1.395188514121991


100%|██████████| 11336/11336 [00:06<00:00, 1881.20it/s]


After graph 11147
After Pruning 4696
start
[Open3D WARNING] Read PLY failed: unable to read file: data_test/pairwise/repair_group8_pair2/RPf_00059_gt.ply


RPly: Error reading value number 2 of 'vertex_indices' of 'face' number 47266


starting init
starting threshold
create graph
my radius is :  2.4937656926096854


100%|██████████| 20914/20914 [00:12<00:00, 1609.46it/s]


After graph 20044
After Pruning 6951
[[ 1.   0.   0.   0. ]
 [ 0.   1.   0.  -0.6]
 [ 0.   0.   1.   0. ]
 [ 0.   0.   0.   1. ]]
[[1.  0.  0.  0. ]
 [0.  1.  0.  0.6]
 [0.  0.  1.  0. ]
 [0.  0.  0.  1. ]]
[[ 8.11536439e-01  5.57646362e-01 -1.74468173e-01 -1.22648052e-02]
 [-5.64323209e-01  6.70619364e-01 -4.81465455e-01  7.22491334e+01]
 [-1.51485725e-01  4.89183200e-01  8.58924835e-01 -1.95969958e+01]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[[  0.81153644  -0.56432321  -0.15148572  37.813151  ]
 [  0.55764636   0.67061936   0.4891832  -38.85830735]
 [ -0.17446817  -0.48146546   0.85892483  51.61566852]
 [  0.           0.           0.           1.        ]]
{'R_error': 1.147971569626019, 'T_error': 75.17293158946697}


{'R_error': 1.147971569626018, 'T_error': 74.28082333175925}

In [5]:
import helper
import numpy as np
import ast
import re
s = '''[[  0.86216055  -0.05210942  -0.50394821  11.1895856 ]
 [ -0.07712327   0.969605    -0.23220281   5.7623569 ]
 [  0.50073065   0.23906224   0.83193633 -41.70132799]
 [  0.           0.           0.           1.        ]]
'''
print(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
M = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
print(M)
RST = np.asarray(M)
R,T = helper.decompose(RST)
print(R)
print(T%3.14)

[[  0.86216055,-0.05210942,-0.50394821,11.1895856 ], [ -0.07712327,0.969605,-0.23220281,5.7623569 ], [  0.50073065,0.23906224,0.83193633,-41.70132799], [  0.,0.,0.,1.        ]]
[[0.86216055, -0.05210942, -0.50394821, 11.1895856], [-0.07712327, 0.969605, -0.23220281, 5.7623569], [0.50073065, 0.23906224, 0.83193633, -41.70132799], [0.0, 0.0, 0.0, 1.0]]
[[ 0.86216055 -0.05210942 -0.50394821]
 [-0.07712327  0.969605   -0.23220281]
 [ 0.50073065  0.23906224  0.83193633]]
[1.7695856  2.6223569  2.25867201]


In [10]:
import transforms3d
Tdash, Rdash, Zdash, Sdash = transforms3d.affines.decompose(RST)

In [12]:
Sdash

array([0., 0., 0.])

In [6]:
s = '''[[ 1.          0.          0.          0.        ]
 [ 0.          0.92106099 -0.38941834  0.        ]
 [ 0.          0.38941834  0.92106099  0.        ]
 [ 0.          0.          0.          1.        ]]'''
print(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
M = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', s).splitlines()))
print(M)
RST = np.asarray(M)
R,T = helper.decompose(RST)
print(R)
print(T)

[[ 1.,0.,0.,0.        ], [ 0.,0.92106099,-0.38941834,0.        ], [ 0.,0.38941834,0.92106099,0.        ], [ 0.,0.,0.,1.        ]]
[[1.0, 0.0, 0.0, 0.0], [0.0, 0.92106099, -0.38941834, 0.0], [0.0, 0.38941834, 0.92106099, 0.0], [0.0, 0.0, 0.0, 1.0]]
[[ 1.          0.          0.        ]
 [ 0.          0.92106099 -0.38941834]
 [ 0.          0.38941834  0.92106099]]
[0. 0. 0.]


In [ ]:
init_R = '''[[ 1.          0.          0.        ]
 [ 0.          0.92106099 -0.38941834]
 [ 0.          0.38941834  0.92106099]]
'''
init_R = ast.literal_eval(','.join(re.sub(r'(?<=[\d+\.\d+])(\s+)(?=-?[\d+\.\d+])', ',', init_R).splitlines()))
init_R

[[1.0, 0.0, 0.0],
 [0.0, 0.92106099, -0.38941834],
 [0.0, 0.38941834, 0.92106099]]

In [ ]:
optimal = np.eye(3)
results = np.matmul(R,np.transpose(init_R))
R_error = (np.sqrt(np.sum(np.square(optimal - results))))
R_error = (np.sqrt(np.sum(np.square(T - results))))

In [45]:
R_error

0.5495921530129283

In [5]:
test1.show_before()

In [6]:
test1.show_after()

In [7]:
test1.save_test()

TypeError: cannot pickle 'module' object

In [10]:
import pandas as pd
import os
from pathlib import Path 
d =  {'col_1': [3, 2, 1, 0], 'col_2': ['a', 'b', 'c', 'd']}
df = pd.DataFrame.from_dict(d)
path = os.path.join("results","ali",'out.csv')
df.to_csv(path)  